src/main.rs
Started implementation of improved scanning, using the .d dep files to filter
out which .rs files are actually used by the build.
=> Added --experimental flag to allow merging WIP features to master.

Cargo.lock, src/main.rs
The idea is to replace all easily spotted panics with Result based errors.
=> Result based error handling (pass 1)

src/lib.rs, src/main.rs
Moved command line argument handling from `lib.rs` to `main.rs`.
Also removed an old and confusing comment.
=> More refactoring

Cargo.toml, README.md, src/format/mod.rs, src/lib.rs, src/main.rs
0.4.2 should be ready with this PR.
=> Prep 0.4.2

src/lib.rs
=> Public API, initial polish

src/lib.rs, src/main.rs
fixes #42 
Let me know if any more documentation and/or help text is needed (in which cases, suggestions would be appreciated)
=> add options to filter dependencies by kind; defaults to Kind::Normal

cargo-geiger/tests/snapshots/mod__test1_package_with_no_deps.stdout.snap, cargo-geiger/tests/snapshots/mod__test2_package_with_shallow_deps.stdout.snap, cargo-geiger/tests/snapshots/mod__test3_package_with_nested_deps.stdout.snap, cargo-geiger/tests/snapshots/mod__test4_workspace_with_top_level_package.stdout.snap, cargo-geiger/tests/snapshots/mod__test5_workspace_with_virtual_manifest.stderr.snap, cargo-geiger/tests/snapshots/mod__test5_workspace_with_virtual_manifest.stdout.snap, cargo-geiger/tests/snapshots/mod__test6_cargo_lock_out_of_date.stdout.snap, cargo-geiger/tests/snapshots/mod__test7_package_with_patched_dep.stdout.snap, geiger/src/lib.rs
=> Bugfix for #71.

cargo-geiger/src/cli.rs, cargo-geiger/tests/snapshots/mod__test1_package_with_no_deps.stdout.snap, cargo-geiger/tests/snapshots/mod__test2_package_with_shallow_deps.stdout.snap, cargo-geiger/tests/snapshots/mod__test3_package_with_nested_deps.stdout.snap, cargo-geiger/tests/snapshots/mod__test4_workspace_with_top_level_package.stdout.snap, cargo-geiger/tests/snapshots/mod__test6_cargo_lock_out_of_date.stdout.snap, cargo-geiger/tests/snapshots/mod__test7_package_with_patched_dep.stdout.snap
Hi, I added a new last row that displays the summary of all rows, also it is colorized, if there is any unsafe row it will be red, if there is any crate that allows unsafe it will be the default and if all of the crates disallows unsafe it will be green. I hope that you found everything okay, tell me if there is something that I should change.
=> added footer with the summary of all rows, fixes #43

Cargo.lock, Cargo.toml, cargo-geiger-serde/Cargo.toml, cargo-geiger-serde/LICENSE-APACHE, cargo-geiger-serde/LICENSE-MIT, cargo-geiger-serde/README.md, cargo-geiger-serde/src/lib.rs
Related to https://github.com/rust-secure-code/cargo-geiger/issues/117
=> Adding a new crate for #117

README.md
=> NOISSUE - Add code coverage badge to readme

README.md
* Add current version on crates.io
* Add total downloads
=> NOISSUE - Add badges to README:

cargo-geiger/src/graph.rs, cargo-geiger/src/main.rs, cargo-geiger/src/mapping.rs, cargo-geiger/src/mapping/metadata.rs
* cargo_metadata replaces/patches when building
* Removing method to use resolve replace function
=> ISSUE-16 - Removing use of replace function:

Cargo.lock, cargo-geiger/Cargo.toml, geiger/Cargo.toml
* Update `syn` package
* Bump `geiger` version
=> ISSUE-5 - Update version of `syn` package used in `geiger`:

cargo-geiger/src/args.rs, cargo-geiger/src/mapping.rs, cargo-geiger/src/mapping/metadata.rs
=> ISSUE-16 - Cleanup a trait only used in a unit test module

cargo-geiger-serde/Cargo.toml
=> Explicitly enable serde for semver

.github/workflows/rust-audit-check.yml
=> ISSUE-166 - Add cargo audit github action to run against head every day

cargo-geiger/src/scan/rs_file.rs
=> ISSUE-116 - Fix into target kind function logic

Cargo.lock, cargo-geiger/Cargo.toml, cargo-geiger/src/scan/find.rs
This commit introduces multithreading for scanning phase in geiger
which is achieved through usage of rayon lib.
Mentions #269
=> Introduce multithreading to scanning phase.

cargo-geiger/src/args.rs, cargo-geiger/src/cli.rs, cargo-geiger/src/main.rs, cargo-geiger/src/mapping/geiger.rs, cargo-geiger/src/tree.rs, cargo-geiger/src/tree/traversal/dependency_kind.rs
* Use is_some() instead of !is_none() in tests
* Remove unnecessary early initialisations
* Use unwrap_or_default
=> NOISSUE - Make cargo clippy recommended improvements:

README.md
=> docs: Clean-up opinion and make the position clearer

cargo-geiger/src/cli.rs, cargo-geiger/src/graph.rs, cargo-geiger/src/main.rs
=> ISSUE-69 - Remove cargo config from graph

CHANGELOG.md, Cargo.lock, cargo-geiger-serde/Cargo.toml, cargo-geiger/Cargo.toml, geiger/Cargo.toml
Thanks @jmcconnell26 and @alexschrod
Fixes #355
=> chore(release): cargo-geiger 0.11.4 geiger 0.4.10 geiger-serde 0.2.3

cargo-geiger/src/scan/default.rs
instead exit with error code + inner error message
EDIT:
Closes #280
=> ISSUE-280 - Don't unwrap when failing to resolve rs file dependencies,

CHANGELOG.md, Cargo.lock, cargo-geiger-serde/Cargo.toml, cargo-geiger/Cargo.toml
Couple of manifest error nits upon release + obligatory changelog
=> Fix 0.12 release nits
