geiger-rs/cargo-geiger

src/main.rs

Since better output formatting was on the roadmap, i tried making the different kinds of unsafe counters more visible by default.
The idea is to have a `(Functions Expressions  Impls  Traits  Methods)` table on the left, and the same radioactive symbol + tree structure + dependency name on the right.
Of couse, the table solution is not the most elegant, and should be factored out along with the tree generation. Similarly, the compact_output flag now passed thru multiple functions should probably be part of some output formatting control struct.
The old output format is kept under the '--compact' switch.
Let me know what you think and if anything should be reworked before it's pullable.

Table-ized output formatting

---

Cargo.lock
Cargo.toml
src/main.rs

Will only ignore `#[test]` functions. Test modules are still counted.

Ignore #[test] functions.

---

src/lib.rs

On Windows 10, the tool does not count files that are actually used in the build, due to a mismatch in the file path representations. 
For example, `cargo geiger -v` gives:
```
Used by build (sorted): \\?\C:\Users\ajpaverd\rust0\src\main.rs
Metric output format: x/y
x = unsafe code used by the build
y = total unsafe code found in the crate
Functions  Expressions  Impls  Traits  Methods  Dependency
Not used in build: C:\Users\ajpaverd\rust0\src\main.rs
0/1        0/1          0/0    0/0     0/0        rust0 v0.1.0 (file:///C:/Users/ajpaverd/rust0)
WARNING: Dependency file was never scanned: \\?\C:\Users\ajpaverd\rust0\src\main.rs
```
I've tested the fixed version on:
- Windows 10
- Windows Subsystem for Linux (Ubuntu 18.04)
- Ubuntu 18.04
I think the fix is quite simple, but please let me …

Canonicalize file paths from walker

---

Cargo.lock
Cargo.toml
src/format/mod.rs
src/lib.rs

Use Rust 2018 edition

---

geiger/src/lib.rs

Separated out the actual source code parsing part from `find_unsafe_in_file`, and made it public. This allows the caller to decided how load the source code to be parsed.
I'm implementing a way to check for unsafe code for [chit](https://github.com/peterheesterman/chit) which downloads the crate and extracts it in memory. Nothing is written to disk, so having a separate function makes using this library a lot more efficient.

Separated out the actual source code parsing part from find_unsafe_in_file, and made it public

---

geiger/Cargo.toml
geiger/src/lib.rs

Bugfix multi forbids

---

Cargo.lock
cargo-geiger/Cargo.toml
cargo-geiger/src/cli.rs
cargo-geiger/src/main.rs

Seems to save about 10 seconds of compile time on my machine.

Replaced structopt & clap with pico-args.

---

Cargo.lock
cargo-geiger/Cargo.toml
cargo-geiger/src/cli.rs
cargo-geiger/src/main.rs

Requires a new dependency on cargo-platform.

Upgrade cargo from 0.40 to 0.41

---

Cargo.lock
README.md
cargo-geiger/Cargo.toml

Fixes: #97 
Is this an acceptable solution? For macOS this seems like the right choice to me. If this PR passes the CI build I'm fine with using the vendored-openssl feature for all platforms.

Expose the cargo crate feature: vendored-openssl.

---

cargo-geiger/src/cli.rs
cargo-geiger/src/graph.rs
cargo-geiger/src/main.rs

Pull code for build_graph into own module, with dependency graph
structure.

ISSUE-16 - Create Graph Module

---

Cargo.lock
cargo-geiger/Cargo.toml
cargo-geiger/src/cli.rs
cargo-geiger/src/format.rs
cargo-geiger/src/format/print.rs
cargo-geiger/src/format/table.rs
cargo-geiger/src/format/tree.rs
cargo-geiger/src/graph.rs
cargo-geiger/src/main.rs
cargo-geiger/src/rs_file.rs
cargo-geiger/src/scan.rs
cargo-geiger/src/traversal.rs

Add unit testing to several of the newly refactored modules, ahead of
migrating to use cargo_metadata
Unit tests added to:
* cli
* format - print
* format - table
* format - tree
* format
* graph
* rs_file
* scan
* traversal

ISSUE-16 - Add unit tests

---

cargo-geiger/src/main.rs
cargo-geiger/src/scan.rs
cargo-geiger/tests/mod.rs

`--quiet` should not take any value based on its description. This is also consistent with usage in most CLI tools.

Make `--quiet` take no value

---

Cargo.lock
cargo-geiger/Cargo.toml
cargo-geiger/src/find.rs
cargo-geiger/src/format/print.rs
cargo-geiger/src/format/table.rs
cargo-geiger/src/main.rs
cargo-geiger/src/report.rs
cargo-geiger/src/rs_file.rs
cargo-geiger/src/scan.rs
cargo-geiger/src/traversal.rs
geiger/Cargo.toml
geiger/src/lib.rs

This adds the ability to generate a JSON report (#35). I reorganized some of the code to avoid duplication and separate scanning from printing more.
Thank you!

Structured output

---

cargo-geiger/src/format/table.rs

The indentation was off. Tested on Linux. I don't have a Mac to test.
Before:
```
2/2        75/75        4/4    1/1     1/1      !  ├── petgraph 0.5.1
0/0        62/62        0/0    0/0     0/0      !  │   ├── fixedbitset 0.2.0
0/0        88/93        1/1    0/0     2/2      !  │   └── indexmap 1.5.0
2/2        954/1048     16/19  0/0     34/38    !  │       └── hashbrown 0.8.1
│           [build-dependencies]
0/0        0/0          0/0    0/0     0/0      ?  │           └── autocfg 1.0.0
│       [build-dependencies]
0/0        0/0          0/0    0/0     0/0      ?  │       └── autocfg 1.0.0
```
After:
```
2/2        75/75        4/4    1/1     1/1      !  ├── petgraph 0.5.1
0/0        62/62        0/0    0/0     0/0      !  │   ├── fixedbitset 0.2.0
0/0        88/93        1/1    0/0 …
```

Fix tree vine on dependency group line

---

.github/workflows/rustfmt.yml

Uses GitHub Actions / actions-rs to ensure code is well-formatted.
I just noticed the rest of CI is using Azure Pipelines (which GitHub Actions uses vicariously, as it were) but hopefully this works well with the existing CI config.

CI: check rustfmt

---

Cargo.lock
cargo-geiger/Cargo.toml
cargo-geiger/src/cli.rs
cargo-geiger/src/graph.rs
cargo-geiger/src/krates_utils.rs
cargo-geiger/src/main.rs
cargo-geiger/src/rs_file.rs
cargo-geiger/src/scan.rs
cargo-geiger/src/scan/default.rs
cargo-geiger/src/scan/default/table.rs
cargo-geiger/src/scan/find.rs
cargo-geiger/src/scan/forbid.rs
cargo-geiger/src/scan/forbid/table.rs
cargo-geiger/src/tree/traversal.rs

* Add krates_utils module to map between cargo PackageId and
cargo_metadata PackageId
* Add methods to cli module to create cargo metadata and krates struct
* Remove usage of cargo PackageId/Package from find module

ISSUE-16 - Staged removal of cargo core:

---

CONTRIBUTING.md

NOISSUE - Add CONTRIBUTING.md file, containing a proposal for

---

cargo-geiger/src/args.rs
cargo-geiger/src/graph.rs
cargo-geiger/src/krates_utils.rs
cargo-geiger/src/main.rs
cargo-geiger/src/scan.rs
cargo-geiger/src/scan/default.rs
cargo-geiger/src/scan/forbid.rs
cargo-geiger/src/tree/traversal.rs
cargo-geiger/src/tree/traversal/dependency_kind.rs
cargo-geiger/src/tree/traversal/dependency_node.rs

* Pull further structs from `Args` struct
* Add functions to krates_utils for `replace` and `deps_not_replaced`
functions from resolve
* Add function for `matches_ignoring_source`
* Adding functions to extract the name and version of a cargo_metadata
package from the `PackageId`
* Remove usage of cargo core from `graph` module

ISSUE-16 - Remove cargo core usage from graph module:

---

azure-pipelines.yml
cargo-geiger/src/args.rs
cargo-geiger/src/cli.rs
cargo-geiger/src/format/display.rs
cargo-geiger/src/format/pattern.rs
cargo-geiger/src/format/print_config.rs
cargo-geiger/src/format/table.rs
cargo-geiger/src/format/table/handle_text_tree_line.rs
cargo-geiger/src/graph.rs
cargo-geiger/src/main.rs
cargo-geiger/src/scan.rs
cargo-geiger/src/scan/default.rs
cargo-geiger/src/scan/default/table.rs
cargo-geiger/src/scan/find.rs
cargo-geiger/src/scan/forbid.rs
cargo-geiger/src/scan/forbid/table.rs
cargo-geiger/src/tree.rs
cargo-geiger/src/tree/traversal.rs
cargo-geiger/src/tree/traversal/dependency_kind.rs
cargo-geiger/src/tree/traversal/dependency_node.rs
cargo-geiger/src/utils.rs
cargo-geiger/src/utils/core.rs
cargo-geiger/src/utils/krates.rs
cargo-geiger/src/utils/metadata.rs

* Remove cargo core usage from scan module
* Remove cargo core usage from traversal module
* Remove cargo core usage from format module
* Remove cargo core usage from scan module
* Refactor krates_utils into separate modules

ISSUE-16 - Remove cargo core usage:

---

cargo-geiger/src/scan.rs
cargo-geiger/src/utils.rs
cargo-geiger/src/utils/metadata.rs

This looks to be the last usage of the cargo::core::PackageId outside of utils that we can move at the minute.
Once this has been updated, I can work through and document what functionality needs to be added to complete the migration, and then work through each one-by-one.

ISSUE-16 - Moving function to create cargo geiger PackageId to utils

---

cargo-geiger/src/format/display.rs
cargo-geiger/src/format/pattern.rs
cargo-geiger/src/format/table.rs
cargo-geiger/src/format/table/handle_text_tree_line.rs
cargo-geiger/src/mapping.rs
cargo-geiger/src/mapping/krates.rs
cargo-geiger/src/scan/default/table.rs
cargo-geiger/src/scan/forbid/table.rs

* Add functions to extract licence and repository from
`cargo_metadata::PackageId`
* Remove `ManifestMetadata` from display
* Add testing

ISSUE-16 - Remove usage of `ManifestMetadata`:

---

cargo-geiger/src/args.rs
cargo-geiger/src/main.rs
cargo-geiger/src/mapping.rs
cargo-geiger/src/mapping/core.rs
cargo-geiger/src/mapping/krates.rs
cargo-geiger/src/mapping/metadata.rs

replicating functionality from `cargo::core::resolve`
* Add query resolve method in mapping
* Move config loading to `Args` module
* Add tests for query to resolve

ISSUE-16 - Add query resolve method to krates mapping package,

---

cargo-geiger/src/format/display.rs
cargo-geiger/src/graph.rs
cargo-geiger/src/main.rs
cargo-geiger/src/mapping.rs
cargo-geiger/src/mapping/core.rs
cargo-geiger/src/mapping/krates.rs
cargo-geiger/src/mapping/metadata.rs
cargo-geiger/src/scan/find.rs

* Implement deps_not_replaced for cargo_metadata
* Update some mapping functions to return options

ISSUE-16 - Implement deps_not_replaced for cargo_metadata:

---

cargo-geiger/src/cli.rs
cargo-geiger/src/format.rs
cargo-geiger/src/format/table/handle_text_tree_line.rs
cargo-geiger/src/graph.rs
cargo-geiger/src/main.rs
cargo-geiger/src/mapping.rs
cargo-geiger/src/mapping/core.rs
cargo-geiger/src/mapping/metadata.rs
cargo-geiger/src/scan.rs
cargo-geiger/src/scan/default.rs
cargo-geiger/src/scan/default/table.rs
cargo-geiger/src/scan/find.rs
cargo-geiger/src/scan/forbid.rs
cargo-geiger/src/scan/forbid/table.rs
cargo-geiger/src/tree.rs
cargo-geiger/src/tree/traversal/dependency_kind.rs
cargo-geiger/src/tree/traversal/dependency_node.rs
cargo-geiger/tests/snapshots/r#mod__test5_workspace_with_virtual_manifest.stderr.snap

* Replace usage of cargo core dependency kind
* Remove use of package set

ISSUE-16 - Remove use of cargo::core:

---

.dockerignore
Dockerfile

* Use cargo chef to reduce docker build times locally
* Add .dockerignore

NOISSUE - Create Dockerfile:

---

cargo-geiger/src/format/table.rs
cargo-geiger/src/main.rs
cargo-geiger/src/scan.rs
cargo-geiger/src/scan/default.rs
cargo-geiger/src/scan/default/table.rs
cargo-geiger/src/scan/forbid.rs
cargo-geiger/src/scan/forbid/table.rs

was found:
* When updating the scanning functions to return results as a vec of
strings, a bug was introduced where the report would only be written
if no warnings were returned

ISSUE-151 - Fix a bug where a report wasn't written if any warning

---

cargo-geiger/src/args.rs
cargo-geiger/src/format/emoji_symbols.rs
cargo-geiger/src/main.rs
cargo-geiger/src/readme.rs
cargo-geiger/tests/readme_integration_tests.rs
cargo-geiger/tests/snapshots/readme_integration_tests__test1_package_with_no_deps.readme.snap
cargo-geiger/tests/snapshots/readme_integration_tests__test2_package_with_shallow_deps.readme.snap
cargo-geiger/tests/snapshots/readme_integration_tests__test3_package_with_nested_deps.readme.snap
cargo-geiger/tests/snapshots/readme_integration_tests__test4_workspace_with_top_level_package.readme.snap
cargo-geiger/tests/snapshots/readme_integration_tests__test6_cargo_lock_out_of_date.readme.snap
cargo-geiger/tests/snapshots/readme_integration_tests__test7_package_with_patched_dep.readme.snap
test_crates/test3_package_with_nested_deps/README.md
test_crates/test4_workspace_with_top_level_package/README.md

* Update args to accept `--readme-path` and `section-name` values
* Add logic to allow custom section names and custom README files
* Add integration test for existing readme cases
* Create new snapshots for README test cases

ISSUE-151 - Accept Readme Path and Section Name as parameters:

---

cargo-geiger/src/args.rs
cargo-geiger/src/format/print_config.rs
cargo-geiger/src/format/table.rs
cargo-geiger/src/format/table/handle_text_tree_line.rs
cargo-geiger/src/scan/default/table.rs

I work on Huawei's Trusted Programming project, which was recently asked to report for Rust projects the "safe ratios", i.e. percentages of items that are safe. This could be done using `cargo-geiger`; however, currently it counts unsafe items, rather than reports the safety ratios,
I've completed a working prototype for this by adding `--output-format=Ratio` as an option to the command. If someone with more experience developing in `cargo-geiger` can give this an early look and send feedback, that would be really helpful.
Apologies in advance for the current lack of tests and limited documentation. I'll be working on this full time for a while, so it will improve rapidly.
Thanks!

Add new Ratio output type --output-format=Ratio

---

geiger/src/find.rs
geiger/src/geiger_syn_visitor.rs
geiger/src/lib.rs

Mark no_mangle functions as unsafe

---

cargo-geiger/src/scan/rs_file.rs

Resolves #78
I'm not sure what could be a better way to handle `unwrap` in this case so I went with the proposed way to clean only package files.

Clean only packages

---

Cargo.lock
cargo-geiger/src/graph.rs
cargo-geiger/src/mapping/krates.rs
cargo-geiger/tests/snapshots/integration_tests__test3_package_with_nested_deps.stdout.snap

crate, which removes the usage of the custom Platform struct, and
replaces with the cargo_platform Platform struct

ISSUE-175 - Update graph module to use latest version of cargo_metadata

---

cargo-geiger/src/tree/traversal/dependency_node.rs

NOISSUE - Remove private enum `PrivateDependencyKind` now cargo_metadata

---

cargo-geiger/src/format/display.rs
cargo-geiger/src/format/table/handle_text_tree_line.rs
cargo-geiger/src/graph.rs
cargo-geiger/src/mapping.rs
cargo-geiger/src/mapping/krates.rs
cargo-geiger/src/mapping/metadata.rs
cargo-geiger/src/readme.rs
cargo-geiger/src/scan.rs
cargo-geiger/src/scan/find.rs
cargo-geiger/tests/snapshots/integration_tests__test2_package_with_shallow_deps.stdout.snap

NOISSUE - Clean up error handling, remove unwrap() calls, logging

---

cargo-geiger-serde/src/lib.rs
cargo-geiger/src/lib.rs
cargo-geiger/src/main.rs
geiger/src/lib.rs

https://github.com/rust-lang/rust/issues/81670 to fix compile warnings
with stable 1.50.0

NOISSUE - Update lint enforcement level based on issue

---

cargo-geiger/src/scan.rs

This gives us easier to read warnings like `error: Found 1 warnings`.

Implement Display for FoundWarningsError instead of relying on Debug

---

cargo-geiger/src/args.rs

Fixes #195.
```console
pest v2.1.3 (/home/ryo/src/github.com/pest-parser/pest/pest)
└── ucd-trie v0.1.3
```
```console
❯ cargo geiger -p ucd-trie
Checking ucd-trie v0.1.3
Checking pest v2.1.3 (/home/ryo/src/github.com/pest-parser/pest/pest)
Finished dev [unoptimized + debuginfo] target(s) in 1.51s
︙
Functions  Expressions  Impls  Traits  Methods  Dependency
2/2        57/57        0/0    0/0     2/2      !  pest 2.1.3
0/0        0/0          0/0    0/0     0/0      ?  └── ucd-trie 0.1.3
2/2        57/57        0/0    0/0     2/2
```
↓
```console
❯ cargo geiger -p ucd-trie
Checking ucd-trie v0.1.3
Checking pest v2.1.3 (/home/ryo/src/github.com/pest-parser/pest/pest)
Finished dev [unoptimized + debuginfo] target(s) in 1.51s
︙
Functions  Expressions  Impls  Traits  Methods  Dependency
0/0 …
```

ISSUE-195 - Fix `Args::parse_args` for `-p` option

---

CHANGELOG.md
cargo-geiger-serde/Cargo.toml
cargo-geiger/Cargo.toml
geiger/Cargo.toml
geiger/README.md

- cargo-geiger 0.11.0
- cargo-geiger-serde 0.2.0
- geiger 0.4.6

Release prep.

---

geiger/src/lib.rs

Re-export public functions of the find module.

---

.github/dependabot.yml

https://deps.rs/repo/github/rust-secure-code/cargo-geiger
**Why?**
- We have some insecure dependencies
- https://deps.rs/repo/github/rust-secure-code/cargo-geiger
- Dependabot will PR (giving the choice) any outdated dependency and tells what has been updated
**Please note**
- Please enable dependabot under repo settings / security 
- Run manually via insights / dependency graph / dependabot (automatic daily otherwise)
- Add labels "deps" and "ci" for PRs so they can be searched/categorised

Adds Dependabot

---

.github/dependabot.yml
.github/workflows/rust-audit-check.yml
.github/workflows/rustfmt.yml
CHANGELOG.md
Cargo.lock
README.md
cargo-geiger-serde/Cargo.toml
cargo-geiger/Cargo.toml
geiger/Cargo.toml
geiger/README.md

**Maintenance release**
- cargo-geiger 0.11.1 -> 0.11.2
- cargo-geiger-serde 0.2.0 -> 0.2.1
- geiger 0.4.7 -> 0.4.8
Bumps various deps as well as removes the annoyances with dependabot custom configuration.
Tests succeed and see no problems.

Maintenance release bump with deps

---

cargo-geiger/src/graph.rs
cargo-geiger/src/mapping.rs
cargo-geiger/src/mapping/metadata.rs

This fixes the issue with `Failed to match` errors, which was caused by cargo-metadata behaviour of not resolving dev-dependencies of crate dependency. 
Now we check if crate is root and if not, we won't collect dev deps for this package, cause they are anyways not in krates graph, which relies on cargo-metadata `resolve` output field.
Also changed argument for `Failed to match` error, cause it mentioned
not the real one unmatched package.
Relates to #240

Fix `Failed to match` errors in cargo-geiger

---

CHANGELOG.md
Cargo.lock
cargo-geiger-serde/Cargo.toml
cargo-geiger/Cargo.toml
geiger/Cargo.toml

- Bump cargo-geiger 0.11.3, geiger 0.4.9, cargo-geiger-serde 0.2.2
- Add threaded scanning [#268]
- Upgraded dependencies including from Cargo 0.58.0 to 0.60.0 [#251], [#275]

chore(release): cargo-geiger 0.11.3, geiger 0.4.9, cargo-geiger-serde 0.2.2

---

cargo-geiger/src/args.rs
cargo-geiger/src/format/print_config.rs
cargo-geiger/src/scan/default/table.rs
cargo-geiger/src/tree.rs
cargo-geiger/src/tree/traversal/dependency_node.rs

possible, and replace with internal `args` representation

ISSUE-69 - Remove usage of `cargo::core::shell::Verbosity` where

---

Cargo.lock
cargo-geiger/Cargo.toml

Takes care of openssl-src to 111.20.0 that pulls 1.1.1o unaffected
Also holds back stum-macro

Bump cargo-update and vendored openssl

---

Cargo.lock
cargo-geiger/Cargo.toml

```
Updating anyhow v1.0.60 -> v1.0.59
Updating backtrace v0.3.65 -> v0.3.66
**Updating bytes v1.1.0 -> v1.2.1**
Updating clap v3.2.8 -> v3.2.16
Updating crossbeam-channel v0.5.5 -> v0.5.6
Updating crossbeam-deque v0.8.1 -> v0.8.2
Updating crossbeam-epoch v0.9.9 -> v0.9.10
Updating crossbeam-utils v0.8.10 -> v0.8.11
Updating curl v0.4.43 -> v0.4.44
Updating curl-sys v0.4.55+curl-7.83.1 -> v0.4.56+curl-7.83.1
Updating fastrand v1.7.0 -> v1.8.0
Updating gimli v0.26.1 -> v0.26.2
Updating hashbrown v0.12.1 -> v0.12.3
Updating itoa v1.0.2 -> v1.0.3
Updating libc v0.2.126 -> v0.2.127
Updating object v0.28.4 -> v0.29.0
Updating openssl v0.10.40 -> v0.10.41
Updating openssl-sys v0.9.74 -> v0.9.75
**Updating os_info v3.4.0 -> v3.5.0**
**Updating os_str_bytes v6.1.0 -> v6.2.0**
Updating proc-macro2 …
```

chore: bumps and fix anyhow .60 y

---

cargo-geiger-serde/src/report.rs
cargo-geiger/src/args.rs
cargo-geiger/src/format.rs
cargo-geiger/src/format/pattern.rs
cargo-geiger/src/format/print_config.rs
cargo-geiger/src/graph/extra_deps.rs
cargo-geiger/src/scan/rs_file.rs
cargo-geiger/src/tree.rs
cargo-geiger/src/tree/traversal/dependency_kind.rs
geiger/src/lib.rs

* `format_push_string` - avoid an extra allocation by using `write!` to
append to an existing string, instead of `format!`
* `derive_partial_eq_without_eq` - ensure that all structs that both
derive `PartialEq` and contain only members that derive `Eq` also
derive `Eq`

NOISSUE - Make cargo clippy recommended changes:

---

CHANGELOG.md
cargo-geiger/src/tree/traversal.rs
cargo-geiger/tests/context/mod.rs

This PR fixes a few typos (trial run for [a CLI I made](https://github.com/Lioness100/rspell))
:rofl:

docs: fix typos

---

cargo-geiger/src/mapping/geiger.rs
cargo-geiger/tests/integration_tests.rs
cargo-geiger/tests/snapshots/integration_tests__test9_package_with_git_deps.stderr.snap
cargo-geiger/tests/snapshots/integration_tests__test9_package_with_git_deps.stdout.snap
test_crates/test9_package_with_git_deps/Cargo.toml
test_crates/test9_package_with_git_deps/src/lib.rs

Fixes #461 
- Instead of harsh `unwrap`, a default empty string is used
- Added unit test case for when `rev` is not defined
Is it something like this we want? This is the simplest fix I can come up with, but perhaps it messes with resolution?
Also, do went a debug message, or should this be a silent solution (after all, if there is no `rev` it should have a sane default)
I have yet to figure out the integration tests

Fix panic when git dependency does not declare revision

---

.github/workflows/release.yml

To enable pushing binaries as part of the release requires a permission isolated to the admin-workflow

Enable GitHub release publish from workflow
